apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-cicd-demo
  namespace: argocd
spec:
  project: default
<<<<<<< HEAD
  source:  https://github.com/MySagarGitHub/Gitops-manifests.git
=======
  source:
>>>>>>> 341e2ed7ab742526b0e040e646851a84ecd8ba15
    repoURL: 
    targetRevision: main  
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
